name: multi_image_picker
description: Flutter plugin that allows you to display multi image picker on iOS and Android.
version: 4.9.1
homepage: https://github.com/idabgsram/multi_image_picker

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: com.guzram.multiimagepicker
        pluginClass: MultiImagePickerPlugin
      ios:
        pluginClass: MultiImagePickerPlugin

environment:
  sdk: ">=2.14.0"
